version: '3.6'
services:
  iris:
    environment:
        - OPENAI_KEY=${OPENAI_KEY}
        - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 57372:1972
      - 57373:52773
      - 57374:53773
    volumes:
      - ./:/home/irisowner/dev
