version: '3.6'
services:
  iris:
    environment:
        - OPENAPI_KEY=${OPENAPI_KEY}
        - TELEGRAM_TOKEN=7194686883:AAHGvYjsfPqjUjdfekwnDdfYZ0uvwH2ERjI
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 1972
      - 52773
      - 53773
    volumes:
      - ./:/home/irisowner/dev
